logitech_lakehouse:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: gold
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 4
      catalog: hive_metastore # or unity_catalog_name

    prod:
      type: databricks
      schema: gold
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 8
      catalog: hive_metastore
